# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ensembl_get": "00_ensembl.ipynb",
         "ensembl_post": "00_ensembl.ipynb",
         "get_ensembl_id_information": "00_ensembl.ipynb",
         "get_transcript_sequence": "00_ensembl.ipynb",
         "post_transcript_sequence": "00_ensembl.ipynb",
         "create_region_str": "00_ensembl.ipynb",
         "get_region_sequence": "00_ensembl.ipynb",
         "post_region_sequences": "00_ensembl.ipynb"}

modules = ["ensembl.py"]

doc_url = "https://gpp-rnd.github.io/sgrna_designer/"

git_url = "https://github.com/gpp-rnd/sgrna_designer/tree/master/"

def custom_doc_links(name): return None
